### ISSUE TITLE
代码里的网络跟论文里不太一样

### ISSUE THREAD

**Issue by ohtiger** [Aichiniuroumian/FSRBARN#1]
作者，你好，感觉你代码里写的网络跟论文里的不太一样，是不是放错代码了

**Comment by Aichiniuroumian** [comment]
> 
您好，非常感谢您的提问，这篇工作主要是在2020年 Chaofeng Chen大佬发表在TIP的SPARNet网络中进行改进的，主要改进有以下两点：
1、在特征提取单元的末端加入了一个多阶特征融合模块
2、将FAU中的空间注意力替换为ISAB
当时整理代码比较仓促，上传的代码可能有些乱，不知道您说的是网络中哪一部分的代码有问题，我好下去重新检查一下~

**Comment by ohtiger** [comment]
不好意思，我看错了。有一篇论文跟你的标题很像，叫做Face Super-Resolution Reconstruction Based on Self-Attention Residual Network。我把你的代码当成这篇文章的代码了。请问你这个工作发表文章了吗，能不能把文章链接发我看一下，想学习一下。

**Comment by Aichiniuroumian** [comment]
> 

您好，这篇工作目前在知网可以查到并下载，题目是《基于注意力残差网络的人脸超分辨率重建》，希望可以帮到您~
